### ISSUE TITLE
Divide by zero exception

### ISSUE THREAD

**Issue by isaacabraham** [elastacloud/mbrace-on-brisk-starter#22]
On exercise "3-comparing threads", line 117 (clusterMultiWorkerMultiThread) I consistently get this exception: -

`System.DivideByZeroException: Attempted to divide by zero.
   at FSI_0009.Array.chunkBy@5.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at FSI_0024.clusterMultiWorkerMultiThreaded@122-21.Invoke(Unit unitVar)
   at MBrace.CloudBuilderUtils.protect[a,b](FSharpFunc`2 f, a s) in C:\dev\github-repositories\MBrace.Core\src\MBrace.Core\Continuation\CloudBuilder.fs:line 12
   at Cloud.Parallel[T](seq<Cloud<T>> computations)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
   at <StartupCode$MBrace-Azure-Client>.$Process.AwaitResultAsync@116-1.Invoke(Result`1 _arg2) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Process.fs:line 116
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@787-1.Invoke(a a)
   at MBrace.Continuation.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in C:\dev\github-repositories\MBrace.Core\src\MBrace.Core\Continuation\ExceptionDispatchInfo.fs:line 134
   at MBrace.Azure.Client.Process`1.AwaitResult() in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Process.fs:line 110
   at <StartupCode$MBrace-Azure-Client>.$Client.RunAsync@103-2.Invoke(Unit unitVar) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 103
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@803.Invoke(AsyncParams`1 args)
   at MBrace.Continuation.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in C:\dev\github-repositories\MBrace.Core\src\MBrace.Core\Continuation\ExceptionDispatchInfo.fs:line 134
   at MBrace.Azure.Client.Runtime.Run[T](Cloud`1 workflow, FSharpOption`1 cancellationToken, FSharpOption`1 faultPolicy) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 125
   at <StartupCode$FSI_0024>.$FSI_0024.main@() in C:\Users\Isaac\Source\Repos\mbrace-on-brisk-starter\src\Demos\3-comparing-threads-and-workers.fsx:line 120
Stopped due to error`

**Comment by eiriktsarpalis** [comment]
Ah, distributed stacktraces, don't you just love them? :)

Looks like a bug in the dividyBy implementation in collections.fsx which
doesn't seem to handle empty arrays

On Tuesday, February 24, 2015, Isaac Abraham notifications@github.com
wrote:

> On exercise "3-comparing threads", line 117
> (clusterMultiWorkerMultiThread) I consistently get this exception: -
> 
> System.DivideByZeroException: Attempted to divide by zero.
> at FSI_0009.Array.chunkBy@5.GenerateNext(IEnumerable`1& next)
> at
> Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
> at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
> at FSI_0024.clusterMultiWorkerMultiThreaded@122-21.Invoke(Unit unitVar)
> at MBrace.CloudBuilderUtils.protect[a,b](FSharpFunc`2 f, a s) in
> C:\dev\github-repositories\MBrace.Core\src\MBrace.Core\Continuation\CloudBuilder.fs:line
> 12
> at Cloud.Parallel[T](seq<Cloud<T>> computations)
> 
> ## --- End of stack trace from previous location where exception was thrown
> 
> at Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
> at <StartupCode$MBrace-Azure-Client>.$Process.AwaitResultAsync@116-1.Invoke(Result`1
> _arg2) in
> C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Process.fs:line
> 116
> at Microsoft.FSharp.Control.AsyncBuilderImpl.args@787-1.Invoke(a a)
> at
> MBrace.Continuation.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1
> workflow, FSharpOption`1 cancellationToken) in
> C:\dev\github-repositories\MBrace.Core\src\MBrace.Core\Continuation\ExceptionDispatchInfo.fs:line
> 134
> at MBrace.Azure.Client.Process`1.AwaitResult() in
> C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Process.fs:line
> 110
> at <StartupCode$MBrace-Azure-Client>.$Client.RunAsync@103-2.Invoke(Unit
> unitVar) in
> C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line
> 103
> at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@803.Invoke(AsyncParams`1
> args)
> at
> MBrace.Continuation.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1
> workflow, FSharpOption`1 cancellationToken) in
> C:\dev\github-repositories\MBrace.Core\src\MBrace.Core\Continuation\ExceptionDispatchInfo.fs:line
> 134
> at MBrace.Azure.Client.Runtime.Run[T](Cloud`1 workflow, FSharpOption`1
> cancellationToken, FSharpOption`1 faultPolicy) in
> C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line
> 125
> at <StartupCode$FSI_0024>.$FSI_0024.main@() in
> C:\Users\Isaac\Source\Repos\mbrace-on-brisk-starter\src\Demos\3-comparing-threads-and-workers.fsx:line
> 120
> Stopped due to error
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/elastacloud/mbrace-on-brisk-starter/issues/22.

## 

Sent from Gmail Mobile

**Comment by isaacabraham** [comment]
Why would there be an empty array?

**Comment by eiriktsarpalis** [comment]
Sorry, I meant passing 0 to `chunkBy`. Which can happen if `n` is larger than the input array length in `divideBy`.

Should be fixed in #23.
