### ISSUE TITLE
error on first-time use

### ISSUE THREAD

**Issue by dimitriv** [elastacloud/mbrace-on-brisk-starter#39]
I created an mbrace cluster using brisk, entered connection strings into samples, built the solution to download the nuget packages and then ran hello-world.fsx but got: 

```
inding session to 'C:\Users\dimitris\work\Azure\mbrace-on-brisk-starter-master\mbrace-on-brisk-starter-master\src\Demos\../../packages/MBrace.Azure.Client/tools\Microsoft.Data.Edm.dll'...
Binding session to 'C:\Users\dimitris\work\Azure\mbrace-on-brisk-starter-master\mbrace-on-brisk-starter-master\src\Demos\../../packages/MBrace.Azure.Client/tools\Microsoft.Data.Services.Client.dll'...
Binding session to 'C:\Users\dimitris\work\Azure\mbrace-on-brisk-starter-master\mbrace-on-brisk-starter-master\src\Demos\../../packages/MBrace.Azure.Client/tools\Microsoft.Data.OData.dll'...
Binding session to 'C:\Users\dimitris\work\Azure\mbrace-on-brisk-starter-master\mbrace-on-brisk-starter-master\src\Demos\../../packages/MBrace.Azure.Client/tools\Newtonsoft.Json.dll'...
System.TypeInitializationException: The type initializer for '<StartupCode$MBrace-Azure-Runtime-Common>.$Config' threw an exception. ---> System.MissingMethodException: Method not found: 'Void Nessos.FsPickler.BinarySerializer..ctor(Microsoft.FSharp.Core.FSharpOption`1<Boolean>, Microsoft.FSharp.Core.FSharpOption`1<Nessos.FsPickler.ITypeNameConverter>)'.
   at Nessos.Vagabond.Daemon.VagabondDaemon..ctor(String cacheDirectory, FSharpList`1 profiles, Boolean requireLoaded, FSharpFunc`2 isIgnoredAssembly, FSharpOption`1 tyConv)
   at Nessos.Vagabond.Vagabond..ctor(FSharpOption`1 cacheDirectory, FSharpOption`1 profiles, FSharpOption`1 typeConverter, FSharpOption`1 isIgnoredAssembly, FSharpOption`1 requireLoadedInAppDomain, FSharpOption`1 loadPolicy) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\Vagabond.fs:line 37
   at Nessos.Vagabond.Vagabond.Initialize(IEnumerable`1 ignoredAssemblies, FSharpOption`1 cacheDirectory, FSharpOption`1 profiles, FSharpOption`1 typeConverter, FSharpOption`1 requireLoadedInAppDomain, FSharpOption`1 loadPolicy) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\Vagabond.fs:line 82
   at <StartupCode$MBrace-Runtime-Core>.$Vagabond.f@1(FSharpOption`1 throwOnError, FSharpFunc`2 factory, Unit unitVar0) in c:\Users\eirik\Development\nessos\MBrace.Core\src\MBrace.Runtime.Core\Vagabond\Vagabond.fs:line 41
   at MBrace.Runtime.Vagabond.VagabondRegistry.Initialize(FSharpFunc`2 factory, FSharpOption`1 throwOnError) in c:\Users\eirik\Development\nessos\MBrace.Core\src\MBrace.Runtime.Core\Vagabond\Vagabond.fs:line 39
   at MBrace.Runtime.Vagabond.VagabondRegistry.Initialize(FSharpOption`1 cachePath, FSharpOption`1 ignoredAssemblies, FSharpOption`1 loadPolicy, FSharpOption`1 throwOnError, FSharpOption`1 cleanup) in c:\Users\eirik\Development\nessos\MBrace.Core\src\MBrace.Runtime.Core\Vagabond\Vagabond.fs:line 66
   at MBrace.Azure.Runtime.ConfigurationModule.init@148.Invoke(Unit unitVar0) in c:\Users\eirik\Development\nessos\MBrace.Azure\src\MBrace.Azure.Runtime.Common\Config.fs:line 149
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at MBrace.Azure.Runtime.ConfigurationModule.runOnce@145.Invoke(Unit unitVar0) in c:\Users\eirik\Development\nessos\MBrace.Azure\src\MBrace.Azure.Runtime.Common\Config.fs:line 145
   at <StartupCode$MBrace-Azure-Runtime-Common>.$Config..cctor() in c:\Users\eirik\Development\nessos\MBrace.Azure\src\MBrace.Azure.Runtime.Common\Config.fs:line 154
   --- End of inner exception stack trace ---
   at MBrace.Azure.Runtime.ConfigurationModule.get_ignoredAssemblies()
   at MBrace.Azure.Client.Runtime..ctor(String clientId, Configuration config) in c:\Users\eirik\Development\nessos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 22
   at MBrace.Azure.Client.Runtime.GetHandle(Configuration config, FSharpOption`1 waitWorkerCount) in c:\Users\eirik\Development\nessos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 401
   at <StartupCode$FSI_0003>.$FSI_0003.main@() in C:\Users\dimitris\work\Azure\mbrace-on-brisk-starter-master\mbrace-on-brisk-starter-master\src\Demos\1-hello-world.fsx:line 22
Stopped due to error
```

**Comment by isaacabraham** [comment]
Which part of the script have you run - the whole lot in one go or just a part of it?

**Comment by dimitriv** [comment]
Ah ok we spotted the problem here with @dsyme. The F# interactive in VS 2012 cannot load the dlls correctly. When I double-clicked on the solution VS 2012 opened. Can you perhaps add a minimal VS version annotation to the project file and/or fix the F# .core dependencies to work with F# 3.0?

FYI the error was happening in this line: 

```
let cluster = Runtime.GetHandle(config)
```

**Comment by isaacabraham** [comment]
There are dependencies on FSharp.Core 4.3.1.0 as far as I know which is F#3.1. Shouldn't that work on VS2012 though @dsyme?

I must admit the versioning and relationship of FSharp.Core, F#3.x and VS201x does confuse me a little.

**Comment by eiriktsarpalis** [comment]
@dimitriv you need to explicitly add a binding redirect to FSharp.Core 4.3.0.0 in your Fsi instance. Find `%PROGRAMFILES%\Microsoft SDKs\F#\3.0\Framework\v4.0\Fsi.exe.config` and add or update the following entry:

``` xml
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity
          name="FSharp.Core"
          publicKeyToken="b03f5f7f11d50a3a"
          culture="neutral"/>
        <bindingRedirect
          oldVersion="2.0.0.0-4.3.1.0"
          newVersion="4.3.0.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

**Comment by dsyme** [comment]
VS2012 F# Interactive --> F# 3.0 --> FSharp.Core 4.0.0.0-4.3.0.0 dependencies
VS2013 F# Interactive --> F# 3.1 --> FSharp.Core 4.0.0.0-4.3.1.0 dependencies
VS2015 F# Interactive --> F# 4.0 --> FSharp.Core 4.0.0.0-4.4.0.0 dependencies

Ideally MBrace binaries should depend only on at most 4.3.0.0 to avoid inducing the VS2013+ dependency (I'd be surprised if there's anything critical in 4.3.1.0 or 4.4.0.0 that MBrace needs, and if there were the above workaround wouldn't work)

**Comment by isaacabraham** [comment]
Is there anything we can do to make this work out-of-the-box for VS2012?

**Comment by dsyme** [comment]
We either make MBrace depend only on FSharp.Core 4.3.0.0, or adjust the solution file to minimally require Visual Studio 2013.

As a workaround, adding the standard ["don't worry, be happy" assembly resolver](http://stackoverflow.com/questions/14578665/f-compile-code-at-runtime-ends-in-missing-assemblies) will probably fix things

```
System.AppDomain.CurrentDomain.add_AssemblyResolve (
    System.ResolveEventHandler (fun _ args ->
        let resolvedAssembly =
            System.AppDomain.CurrentDomain.GetAssemblies ()
            |> Array.tryFind (fun loadedAssembly ->
                // If this assembly has the same name as the one we're looking for,
                // assume it's correct and load it. NOTE : It may not be the _exact_
                // assembly we're looking for -- then you'll need to adjust the critera below.
                args.Name = loadedAssembly.FullName
                || args.Name = loadedAssembly.GetName().Name)

        // Return null if the assembly couldn't be resolved.
        defaultArg resolvedAssembly null))
```
